---
# Site configuration

site:
    # global parameters on the site (assuming single main site)
    base_url: http://localhost:5000

output:
    dir: out/run_{pid}
    tempdir: out/run_{pid}/tmp

browser:        # Technical conf about the browser
    engine: chrome
    launch_on: feature  # or 'scenario' or 'demand'
    window: 1200x700
    # more capabilities...
    # headless: true
    headless: false
    # implicit_wait: 500ms

    screenshots:
        dir: screenshots
        on_failure: true

    downloads:
        allow: True

page_objects:
    index: site/index.html
    # root_controller: .root
    # page_controller: page
