---
# Site configuration

site:
    # global parameters on the site (assuming single main site)
    base_url: https://material.angular.io

browser:        # Technical conf about the browser
    engine: chrome
    launch_on: feature  # or 'scenario' or 'demand'
    soft_change: true
    # change_retries: 3
    window: 1000x500
    # more capabilities...
    # headless: true
    headless: false
    implicit_wait: 500ms

    screenshots:
        dir: screenshots
        on_failure: true

page_objects:
    index: site/index.html
    # root_controller: .root
    page_controller: app.angular
