---
# Site configuration

site:
    # global parameters on the site (assuming single main site)
    base_url: https://seleniumhq.github.io/selenium/docs/api/py/
    element_timeout: 1000ms

browser:        # Technical conf about the browser
    engine: chrome
    launch_on: feature  # or 'scenario' or 'demand'
    window: 1600x900
    # more capabilities...
    # headless: true
    headless: false

page_objects:
    index: site/index.html
