---
# Site configuration

site:
    # global parameters on the site (assuming single main site)
    base_url: https://angular.io/
    # no: implicit_wait: 1000ms

browser:        # Technical conf about the browser
    engine: chrome
    launch_on: feature  # or 'scenario' or 'demand'
    window: 1200x700
    # more capabilities...
    # headless: true
    headless: false

    screenshots:
        dir: screenshots
        on_failure: true

page_objects:
    index: site/index.html
    # root_controller: .root
    page_controller: app.angular
