---
# Site configuration

site:
    # global parameters on the site (assuming single main site)
    base_url: https://developer.mozilla.org/en-US/docs/Web
    element_timeout: 1000ms

browser:        # Technical conf about the browser
    engine: chrome
    launch_on: feature  # or 'scenario' or 'demand'
    window: 1600x900
    # more capabilities...
    # headless: true
    headless: false
    
    screenshots:
        dir: screenshots
        on_failure: true
        on_success: true

page_objects:
    index: site/index.html
